### ISSUE TITLE
Citro2d Examples

### ISSUE THREAD

**Issue by Magicrafter13** [devkitPro/citro2d#1]
Are there any examples created yet for this? Since pp2d no longer exists, I would like to use citro2d in my future projects, but I have no idea how to implement it.

**Comment by fincs** [comment]
They're part of 3ds-examples:

https://github.com/devkitPro/3ds-examples/tree/master/graphics/gpu/gpusprites
https://github.com/devkitPro/3ds-examples/tree/master/graphics/gpu/composite_scene
https://github.com/devkitPro/3ds-examples/tree/master/graphics/printing/system-font

**Comment by Magicrafter13** [comment]
I hate bugging you constantly, but I built the example (had to install tex3ds real quick, but it was easy to do). Example built fine, I load it on my sd card, and I tried to run it on my 3ds. I got a "An exception occurred" error screen. Access type: read.

I tried to rebuild it again to see if something went wrong the first time, still built fine, but still crashed my system. Do I need to perform a system update or something?

And also, would you like the crash dump?

**Comment by fincs** [comment]
It looks to me like you either do not have an up-to-date toolchain install, or you have a corrupted/tampered toolchain install. I would suggest to completely erase all traces of all previous toolchain installs, then [proceed with the installation instructions](https://3dbrew.org/wiki/Setting_up_Development_Environment) appropriate for your operating system, making sure you are using the latest stable releases of all packages contained in the `3ds-dev` group. Then afterwards try to build the gpusprites example, and see if you get a working binary. If, despite this process, it still doesn't work then we can perform further troubleshooting.

**Comment by Magicrafter13** [comment]
That did the trick.
I have some more questions but I don't know if this is the place for them, do you have Discord?

**Comment by fincs** [comment]
We don't use Discord, we use IRC. You can find us at #3dsdev @ EFnet.
