### ISSUE TITLE
Help understanding C2D_ImageTint

### ISSUE THREAD

**Issue by Magicrafter13** [devkitPro/citro2d#10]
I have a plain white PNG in my sprite sheet, and I want to draw it with different colors. It's a 1x1 full white pixel. My idea is to use C2D_DrawImageAt to stretch, rotate, and color the image so I can essentially draw lines (since this feature isn't already built in for some reason). I would use rectangles, triangles, or ellipse', but I don't want them filled in, plus I just need plain lines anyway.

My problem is that I don't understand how to create a C2D_ImageTint. I looked at the documentation but I don't understand that either.

**Comment by fincs** [comment]
Basically, an ImageTint is a collection of colors that are applied to a quad. There are four colors, one for each corner. The PICA interpolates colors everywhere else in the quad, forming gradients. You can use C2D_SetImageTint to set the color corresponding to a corner directly, or one of the helper functions (C2D_PlainImageTint for a single solid color, C2D_AlphaImageTint for transparency, C2D_Top/Bottom/Left/RightImageTint for tinting the sides of the quads).

Also, this is an issue tracker, used to track bugs and feature requests. Support questions and assistance are better handled on official channels such as EFnet #3dsdev or the [devkitPro forums](https://devkitpro.org/).

**Comment by Magicrafter13** [comment]
Since the topic was brought up, could I submit a formal feature request for a function along the lines of C2D_DrawLine? (If so, do you have a feature request template you'd like me to follow?)

**Comment by fincs** [comment]
Lines cannot be drawn efficiently on the PICA200. You'd have to either draw degenerate triangles (I'm not sure if those work at all), or draw rotated rectangles.

**Comment by Magicrafter13** [comment]
Interesting, and I suppose I'll try triangles. I'd do rectangles, but I need to specify the corners, and I assume the rotation would change that, plus I didn't find a function to draw rotated rectangles.

For the record, just because something is inefficient, doesn't necessarily make it a bad feature imo. In my case anyway, I only want to use this for testing my game, and they wouldn't be in the final code.

**Comment by fincs** [comment]
The main motivation for citro2d was creating a helper library that would allow users to perform common 2D tasks *efficiently* on the PICA200. Adding a feature that is inefficient is against the design goals of citro2d.
