### ISSUE TITLE
How to draw an image with C2D_Image??

### ISSUE THREAD

**Issue by Pecacheu** [devkitPro/citro2d#16]
Hi, I doubt this library is even maintained anymore now that the Switch is out, but I have a bit of an issue with using C2D_Image to draw an image.

Here's my relevant test code. It's fairly simple and the result should just be a gradient that sets the RGB from 0 to 255 and then loops until it runs out of pixels.
```
C2D_Image *createTest() {
	u32 w=32, h=32;
	C3D_Tex *tex = new C3D_Tex;
	if(!C3D_TexInit(tex,w,h,GPU_RGBA8)) return NULL;

	u32 s=w*h, *b = (u32*)linearAlloc(s*4); u8 n=0;
	for(u32 ofs=0; ofs<s; ofs++) { b[ofs] = C2D_Color32(255,n,n,n); n++; }

	C3D_TexUpload(tex,b); Tex3DS_SubTexture *subtex = new Tex3DS_SubTexture;
	subtex->left=subtex->top=0; subtex->width=w*4; subtex->height=h*4; //Draw at 400% scale.
	subtex->right=subtex->bottom=1; return new C2D_Image {tex,subtex};
}
```

Only the result is well... Kinda trippy? Is my 3DS high? This happens on both a USA O3DS and a JPN N3DS. I figured it woud be easy enough, I'd just figure out what it's doing and put data in the buffer in a way that compensates for it... Only I've tried a few different tests with different colors/patterns/etc, and I can't really figure out what the pattern is. I'm stumped, what's wrong with this thing?

![3DS Image](https://i.imgur.com/QHFBI1i.jpg)

**Comment by fincs** [comment]
Textures on 3DS aren't stored in a linear format, they undergo tiling and swizzling. That's the reason why we have a [specialized texture conversion tool](https://github.com/devkitPro/tex3ds) that reads image files in common formats, performs the necessary conversions, and outputs files that can be more easily used on the 3DS.

**Comment by Pecacheu** [comment]
Is it possible to do this at runtime? In my program I need to be able to generate/alter some sprites dynamically. I can't imagine rearranging the bytes in a few sprites could take that long, and it only needs to be done once per sprite.

But I have no idea what the pattern in question is so I can't write a conversion function. Some code would be helpful.

**Comment by mtheall** [comment]
https://github.com/devkitPro/tex3ds/blob/master/source/swizzle.cpp

**Comment by fincs** [comment]
The code @mtheall pointed to is an implementation of the swizzling algorithm. However, this should be used sparingly (if at all) at runtime. It would still be preferable to just have pre-converted variants of your sprite; depending on the nature of the "alterations" you need for your sprites.

**Comment by piepie62** [comment]
Just want to point this out, some of the sprites you're trying to generate/alter might be easily doable with the utilities already provided. The gradient that you're trying to make in that example, for example, could be done with a couple of triangles fairly easily

**Comment by Pecacheu** [comment]
So I think I've ported this correctly, I can't find any problems with the code itself, but it's still not working right. (This is hardly an issue with C2D at this point though, of course)

```
struct ImgPart {
	ImgPart(BmpImage& b, u32 x, u32 y, u32 w):b(b),x(x),y(y),w(w) {}
	u32& operator[] (u32 i) { return ((u32*)b.b)[(y + i/w)*b.w + x + i%w]; }
	BmpImage& b; u32 x,y,w;
};

const u8 szTab[][4] = {
	{  2,  8, 16,  4}, {  3,  9, 17,  5},
	{  6, 10, 24, 20}, {  7, 11, 25, 21},
	{ 14, 26, 28, 22}, { 15, 27, 29, 23},
	{ 34, 40, 48, 36}, { 35, 41, 49, 37},
	{ 38, 42, 56, 52}, { 39, 43, 57, 53},
	{ 46, 58, 60, 54}, { 47, 59, 61, 55}
};

inline void swapPix(u32& p1, u32& p2) { u32 c=p1; p1=p2; p2=c; }

void szPart(ImgPart p, bool undo) {
	u32 c; if(undo) for(const auto &e: szTab) {
		c = p[e[3]]; p[e[3]] = p[e[2]]; p[e[2]] = p[e[1]];
		p[e[1]] = p[e[0]]; p[e[0]] = c;
	} else for(const auto &e: szTab) {
		c = p[e[0]]; p[e[0]] = p[e[1]]; p[e[1]] = p[e[2]];
		p[e[2]] = p[e[3]]; p[e[3]] = c;
	}
	swapPix(p[12], p[18]); swapPix(p[13], p[19]);
	swapPix(p[44], p[50]); swapPix(p[45], p[51]);
}

void swizzle(BmpImage& b, bool undo = 0) {
	for(u32 y=0,x; y<b.h; y+=8) for(x=0; x<b.w; x+=8)
		szPart(ImgPart(b,x,y,8), undo);
}
```

The BmpImage struct is defined elsewhere as:
```
struct BmpImage {
	const u8 *b; u32 w,h;
	u16 bits; size_t size;
};
```
I'm just using it as a general image container format. Then adding the line `BmpImage br {(u8*)b,w,h}; swizzle(br);` into the test function to do the swizzling (whatever that is).

And my (heavily simplified) render loop to help if you want to test:
```
/* Other init things */
C3D_RenderTarget *sTop = C2D_CreateScreenTarget(GFX_TOP, GFX_LEFT);

u32 clrClear = C2D_Color32(50, 50, 50, 255);
C2D_Image *img = createTest(); if(!img) { exit(); return 6; }

while(aptMainLoop()) {
	hidScanInput(); kDown = hidKeysDown();
	if(kDown & KEY_START) break; //Exit

	C3D_FrameBegin(C3D_FRAME_SYNCDRAW);
	C2D_TargetClear(sTop, clrClear); C2D_SceneBegin(sTop);
	C2D_DrawImageAt(*img, 20, 20, 0);
	C3D_FrameEnd(0);
}
```

Anyhow, the end result looks like this, so... closer I guess?

![3DS Image](https://i.imgur.com/B4WoqJR.jpg)

**Comment by WinterMute** [comment]
> Is it possible to do this at runtime? In my program I need to be able to generate/alter some sprites dynamically. I can't imagine rearranging the bytes in a few sprites could take that long, and it only needs to be done once per sprite.

Can you be more specific about what exactly it is you want to do? What you're describing here is a pretty inefficient way to make use of the GPU in both CPU and memory terms. If it only needs to be done once per sprite then why can't it be done at buildtime? 

It's difficult to offer help that isn't somewhat abstract if you don't fully describe the problem.


> But I have no idea what the pattern in question is so I can't write a conversion function. Some code would be helpful.

You don't need to write a conversion function, don't get caught up in this - it will end up limiting what you can do with the hardware & lead to frustration.

**Comment by Pecacheu** [comment]
Well I have two different projects I'm trying to use this code in. Both of which I had (mostly) working in SF2D before. But SF2D is discontinued and no longer works.

For the first I need to load in sprites and just recolor specific parts of them. Maybe this is possible in C2D using some kind of image mask and tinting, but I was using raw pixel manipulation before.

Second application needs two things. Firstly to load graphics/sprites in dynamically over the network (so basically, assume 100% dynamic), and secondly, to load in OTF format fonts, also dynamically.

For that I had ported over an OTF font library and then created a library that converts the glyphs into sprites and handles text and character widths and all that.

But anyway, if doing this in runtime is causes problems than how come that's how they decided to make it work with SF2D? You could just put in an image with normal pixel order and get out a sprite.

**Comment by fincs** [comment]
> how come that's how they decided to make it work with SF2D? You could just put in an image with normal pixel order and get out a sprite.

That library did a bunch of inefficient things, such as converting all graphics at runtime or putting every single drawn object under an individual draw call. citro2d was precisely designed to **avoid** said design in order to improve performance. I'm not sure what this "recolor specific parts of them" thing is; could you explain further?

Also, there is an already supported font format (bcfnt). You can convert normal PC fonts using the also included `mkbcfnt` tool.

**Comment by WinterMute** [comment]
They did it that way in SF2D because of inexperience and refusal to listen to people who told them how to do things in a more efficient and maintainable way.

This remains a source of unbelievable frustration - inexperienced people writing "easy" libraries that homebrewers learn bad habits from which ultimately restrict what they can achieve with their homebrew.

The problem we then face is the arduous task of helping frustrated homebrewers let go of poor designs that are actually holding them back. This, in turn, takes much time away from improving tools and trying to write good examples that fill the needs of our users.

**Comment by Pecacheu** [comment]
@WinterMute I get that, but it also had a lot of features useful to my purposes. Would it not be useful to have a C2D example of how to compute at runtime, as it's possible that it might be necessary in some use cases?

> I'm not sure what this "recolor specific parts of them" thing is; could you explain further?

Well, the second project is more of a utility and harder to describe, but the former is just a simple 2D game. In it I had a color slider (Well a few of them for different parts) to set your character's color, which recolored only the outfit, not the skin (cause that'd be weird). But it's not like I can't pre-render a sprite for every single possible RGB color! So I simply used pixel manipulation. And I only had to re-render the sprite while the user was in the menu.

As for the second project it's far more dynamic. The sever is pretty much telling the 3DS what graphics, text, and controls to display. Optimally the server is blind to what type of devices are connected. There are clients for different platforms, and the 3DS is one of them.

Thus I don't want to bog down the server with converting images and fonts *specifically for the 3DS*, like it's some elderly man who needs assistance to hold it's own against so much as a cheap unbranded Android tablet.

> Also, there is an already supported font format (bcfnt). You can convert normal PC fonts using the also included `mkbcfnt` tool.

In that case it might be possible to convert fonts on the server-end. But I'd rather not do things server-side as I said, and the previous code with OTF was working fine, plus it supported hinting and kerning.

Unless that font format is GPU accelerated (as in even glyph/text layout calculation is done in hardware and not by the font library), I see no reason there would be a performance advantage. Glyphs are glyphs.

**Comment by piepie62** [comment]
BCFNTs are raster fonts, which are far better on a limited system such as the 3DS. Also, the 3DS *doesn't* hold its own against "so much as a cheap unbranded Android tablet"; its processor and GPU are far slower than (1/4 the speed of) my tablet from 2012. The first problem you described (recoloring specific parts of sprites) would be easily solved by separating the clothing and the rest of the body from each other. I don't have a good solution for your second problem in mind, partially because I don't understand the point of it or how it actually works

**Comment by piepie62** [comment]
Furthermore, with the recoloring, you can use the color blending that C2D provides so you don't even need to manipulate the images themselves

**Comment by Pecacheu** [comment]
Hmm, I suppose separating the outfit out as a separate sprite would work. Still, it would use double the RAM for double the sprites, so it's not like it has absolutely no trade-off. But I think there's more than enough memory for it.

As for the other thing, it's basically an IoT control app, and it may need to display a variety of different controls for different products which is why it's so dynamic. Might want to show a custom color wheel, for example, or an icon for a given product.

Plus if something needs time to be rendered, I can always preload a loading wheel icon and spin that around to keep one entertained.

And as for the fonts, vector fonts seem like a better idea to me than raster fonts frankly. I'd need a separate version of every glyph for every font size I'd need to display. Even at the O3DS's power it was able to calculate an anti-alias every glyph in the blink of an eye.

**Comment by piepie62** [comment]
"It would use double the RAM for the sprites" If you're using tex3ds properly, it very likely will not. You should be letting tex3ds generate a single spritesheet out of all of your sprites that you grab pieces of using the included tex3ds sprite/image functions.

**Comment by Pecacheu** [comment]
I was using individual images for each walk cycle frame, but yeah a sprite sheet would be a better idea probably.

But even still, I'd need a sprite for the outfit and a separately maintained sprite for the character, both of which I'd move together to make them appear to be a single sprite to the player. So it would still be more RAM.

**Comment by piepie62** [comment]
Certainly. More usage, yes, double usage, no. Anyway, as it is for the fonts, the 3DS has such a low resolution that even the system itself uses raster fonts. if I remember correctly,the glyph height used is 24 pixels. The speed increase from not having to actually create the glyphs dynamically far outweighs the miniscule benefits of kerning and antialiasing, in my opinion, but I believe that freetype is ported if you really care that much

**Comment by fincs** [comment]
Locking due to the discussion migrating to a different topic than the OP.
