### ISSUE TITLE
C2D_AlphaImageTint does not behave as expected

### ISSUE THREAD

**Issue by geniiii** [devkitPro/citro2d#17]
![image](https://user-images.githubusercontent.com/24881499/74092832-4f2a9600-4ad2-11ea-8ad1-0c9a2445a699.png)
The bottom tetromino is being drawn with a C2D_ImageTint, to which the only operation performed was `C2D_AlphaImageTint(&GHOST, 100);`. The tint has no effect, due to the blending strength being set to 0.
```cpp
static inline void C2D_AlphaImageTint(C2D_ImageTint* tint, float alpha)
{
	C2D_PlainImageTint(tint, C2D_Color32f(0.0f, 0.0f, 0.0f, alpha), 0.0f);
}
```
(`base.h:137`)
I'm not too sure whether this is intended or not, but the documentation leads me to believe it isn't.

**Comment by fincs** [comment]
[RGB tint is interpolated using the blending strength; alpha tint is just straight up multiplied](https://github.com/devkitPro/citro2d/blob/master/source/base.c#L464-L473). Also, alpha ranges from 0.0f to 1.0f. 100 is casted down to 1.0f. You probably want 0.4f (which is approximately 100/255).

**Comment by geniiii** [comment]
> [RGB tint is interpolated using the blending strength; alpha tint is just straight up multiplied](https://github.com/devkitPro/citro2d/blob/master/source/base.c#L464-L473). Also, alpha ranges from 0.0f to 1.0f. 100 is casted down to 1.0f. You probably want 0.4f (which is approximately 100/255).

Oh. Wow. I.. don't think I realized alpha is a float.
