### ISSUE TITLE
Add view manipulation

### ISSUE THREAD

**Issue by BubbleChien** [devkitPro/citro2d#2]
I don't know if it's already on the table or not, but it would be nice to add basic view manipulation (a global matrix transformation applied before drawing the sprites). In the current state there doesn't seem to be a simple way to do this through C2D, please tell me if I missed something.

I guess it could look something like that, modeled after the C2D_Sprite functions :

`C2D_ViewSetPosition(x, y);`  
`C2D_ViewMove(x, y);`
`C2D_ViewSetRotation(z);`  
`C2D_ViewRotate(z);`  
`C2D_ViewSetScale(x, y);`  
`C2D_ViewScale(x, y);`

**Comment by fincs** [comment]
This is planned.

**Comment by fincs** [comment]
Don't close it, it's not implemented yet :p

**Comment by fincs** [comment]
Implemented by PR #22.
