### ISSUE TITLE
C2D_DrawTriangle won't render after Rendering a C2D_Image

### ISSUE THREAD

**Issue by pyroticinsanity** [devkitPro/citro2d#20]
Hi,
I'm working on rendering a set of PNG images in my game using C2D_DrawImage but when I try to go back to my game it doesn't render any of the triangles anymore. If I go back to the image, it loads fine and renders again. I've checked the output of C2D_DrawTriangle and it says it is successful so I'm not sure why it isn't rendering.

I've broken it down to a simple example of swapping the scene here: https://github.com/pyroticinsanity/3dsdod/tree/issue2_manual/test/scene_swap.

I've also attached a copy of the 3dsx file if you'd like to check it out.

Any help would be greatly appreciated!
[scene_swap.zip](https://github.com/devkitPro/citro2d/files/4653206/scene_swap.zip)

**Comment by fincs** [comment]
We recommend usage of tex3ds's native formats instead. Is there any specific reason why you need to load png images instead of a native format?

**Comment by pyroticinsanity** [comment]
The main reason is I don't want to package copyrighted material in my game so I was going to get the users to put it on their SD card if they wanted that functionality.

**Comment by Oreo639** [comment]
Are you are using the latest release of libctru, citro3d and citro2d? I tried building your scene_swap example myself and I cannot reproduce the issue in your build.
(You can update your packages by running `(dkp-)pacman -Syu`)

**Comment by pyroticinsanity** [comment]
Thanks for trying it out! You are correct. I'm one version behind and that apparently makes all the difference. I'll remember to check for updates next time.
