### ISSUE TITLE
C2D_ Functions Are Undefined

### ISSUE THREAD

**Issue by Wilderness1265** [devkitPro/citro2d#21]
I wanted to learn more about how to make basic shapes for the 3DS because I wanted to do more than just text. And for some reason every single time I use a C2D function and try to build the file, it always says it's undefined in the terminal in a header file. I don't know what's causing it to happen.

![Undifined Reference](https://user-images.githubusercontent.com/66174169/85959839-daff6a80-b96c-11ea-8b46-e5546dd46c05.png)

**Comment by WinterMute** [comment]
You need to link the libraries you're using. Use one of the citro2d examples as a starting point, not the hello world example. Try /opt/devkitpro/examples/3ds/graphics/gpu/2d_shapes/ for example.
