### ISSUE TITLE
No "ClearRectangle" functionality, or no ability to change alpha blending on 2D "primitives"

### ISSUE THREAD

**Issue by randomouscrap98** [devkitPro/citro2d#29]
I'm trying to use off-screen render targets as layers in a drawing application. Regardless of the use case though, it would be nice to be able to clear an arbitrary section, as in set a rectangle or such to all-transparent (not the whole target). 

Alternatively, if this is "not possible", it would be nice to be able to change the blending modes used for 2D primitives (I understand if this is difficult for circles). I would like to have the option to do pure overwrites for all channels (including the alpha channel) rather than blending with the target when drawing triangles/rectangles/etc. Considering that something similar is being performed to get circles to work, I don't see why this would be "outside the realm of an efficient 2D library". 

This seems to be a common question, "Why do you want to do this?". Imagine you have a rasterized image produced from many many applications of drawing commands. Something that is difficult to reproduce on the fly. And then I want to draw, for instance, a semi-transparent blue rectangle and have it completely overwrite the pixels underneath it. Maybe I'm drawing a window or something. Perhaps I'm not understanding, but this doesn't seem like it'd be inefficient to perform, and it would greatly increase the usability of the library.

Currently, the library is a perfect fit for this drawing application I'm working on save for this one missing feature. I don't want to have to give up and redo everything with Citro3D just because this one thing isn't available.

**Comment by fincs** [comment]
citro3d and citro2d are designed to be usable concurrently. In addition, citro2d does not alter alpha blending state in any way. You're free to use C3D_AlphaBlend to change blending settings as you see fit.

**Comment by randomouscrap98** [comment]
Oh goodness, I cant tell you how much I appreciate that! I've been trying for days, asking all over the place (including the devkitpro forums) just trying to do this simple thing. This is such a relief, thank you. Sorry for making an issue for something at already exists.
