### ISSUE TITLE
C2D_DrawLine preserves alpha of target if it's the first primitive to be rendered (off-screen render target?)

### ISSUE THREAD

**Issue by randomouscrap98** [devkitPro/citro2d#32]
As stated, if you for example call C2D_DrawLine without any other shapes within a standard render loop (with all the appropriate calls etc.), it appears to use the alpha of the target that it is being drawn to rather than the alpha supplied in the color passed in the C2D_DrawLine call. However, if for instance, C2D_DrawRectangle is called first in the loop, then C2D_DrawLine, the alpha is properly set. 

I've only tried it on off-screen render targets. One of the interesting quirks I found (which suggests that drawline is using purely the alpha from the target rather than just not showing at all), is if you run your code from the hb-menu, create an off-screen render target but don't clear it, then try to draw lines into it. The render target will have some of the effects from the hb-menu, and the lines will be MOSTLY transparent, same as the transparency that exists in the target (or so it seems). If you instead fully clear the target with full transparency, then try to do C2D_DrawLine as the first primitive in your render loop, nothing will show up at all (presumably because it is using the 0 alpha present in the target). 

I can provide a full code example if it will help.

**Comment by fincs** [comment]
Seems like this bug was fixed in https://github.com/devkitPro/citro2d/commit/2091947af4aec8d67d98234a27f3352b6274bc50, but then a feature contributed at the same time in https://github.com/devkitPro/citro2d/commit/990deaa95f78a7b1fe21a2ac0b5a2c22b3c7a1ae didn't have the same bugfix applied, in other words, a PR "conflict" that was left unnoticed. Thanks for catching this.

**Comment by randomouscrap98** [comment]
Ah awesome, I'm glad it worked out!
