### ISSUE TITLE
C2D_Text Struct contains a width data field but not the height

### ISSUE THREAD

**Issue by EimaMei** [devkitPro/citro2d#35]
When I was looking at the [documentation](https://citro2d.devkitpro.org/structC2D__Text.html) about C2D_Text, I noticed that it had a `width` data field, which was useful for me since I needed it for my 3DS project. However, a `height` data field was never mentioned anywhere in the struct nor in text.h, so I would have to guess it doesn't exist. Why does `width` exist but not with `height`? Is it even possible to get the height for the text?

**Comment by mtheall** [comment]
"Height" is a font attribute. It doesn't depend on the text unless you have newlines or word wrapping.

See the "height" and "ascent" fields of FINF_s which you can retrieve via C2D_FontGetInfo.

**Comment by mtheall** [comment]
You probably want to use C2D_TextGetDimensions

**Comment by EimaMei** [comment]
That explanation makes sense. I checked out `C2D_TextGetDimensions` as you recommended and it works perfectly. Thanks!
