### ISSUE TITLE
Need a tutorial or examples

### ISSUE THREAD

**Issue by ACIDULATED** [devkitPro/citro2d#36]
This needs a tutorial or examples, it doesn't seem like there is already.

**Comment by NyankoTear** [comment]
You can find some examples from the [devkitPro/3ds-examples](https://github.com/devkitPro/3ds-examples). In my case, [gpusriptes](https://github.com/devkitPro/3ds-examples/tree/master/graphics/gpu/gpusprites) was really helpful.
