### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by valentinvanelslande** [devkitPro/citro2d#4]
Program: [SMM3DSSE](https://github.com/valentinvanelslande/SMM3DSSE)
I get a lot of errors on my citra build #337 with hardware renderer, no errors with software rasterizer

**Comment by fincs** [comment]
But, does it work on real hardware?

**Comment by valentinvanelslande** [comment]
idk

**Comment by fincs** [comment]
Please test it on hardware. We don't consider "not working on emulator" as a bug. Chances are there are no actual problems in neither your program nor in citro2d. Also make sure your copy of Citra is up to date.

**Comment by valentinvanelslande** [comment]
i don't have a 3ds. i think it will crash on hardware
the issue happens in ctrlib (the library that SMM3DSSE uses) ui code.

**Comment by fincs** [comment]
How are you sure that it will crash on hardware, when you don't actually have hardware?
