### ISSUE TITLE
Not linking correctly

### ISSUE THREAD

**Issue by NJxByteTheFox** [devkitPro/citro2d#48]
### What's the issue you encountered?

When compiling a project with citro2d and 3D linked in the makefile \(under LIBS\) 

Citro2d is linked as some errors are appearing in C2D_Init

Citro3d is facing the same issues

```
LIBS := -lctru -lm -lcitro2d -lcitro3d
```

I am getting undefined references to these functions:

* linearAlloc
* DVLB_ParseFile
* shadeProgramInit
* shaderProgramSetVsh
* shaderProgramGetUniformLocation
* linearFree
* gfxIsWide
* C2Di_CalcQuad
* C3Di_attrInfoBind
* GPUCMD_Add
* and several others related to memory/gpu usage

### How can the issue be reproduced?

I do not know

### Environment?

- What host OS are you using?
  Debian 12
  - it can be useful for us to see the output from env.txt on your system. Please redact any personal information.
  I cannot find that file
  - For windows users we often find that use of cmd shell or powershell to be the source of the problem. Please use the supplied msys2 shell.
- Official release or unofficial/self-compiled build: 
  - Please note we only support binaries we supplied. We'll do our best but unfortunately all too often problems with self compiled tools and/or libraries can not be replicated with those distributed via our pacman repos.

### Additional context?

- Additional info about your environment:
HP Elitebook 8570p

DKP latest as of August 2024

Makefile is default for the Application makefile template with added libs

**Comment by WinterMute** [comment]
You need to specify libs in the right order`LIBS := -lcitro2d -lcitro3d  -lctru -lm`

**Comment by NJxByteTheFox** [comment]
Yes I figured that out
