### ISSUE TITLE
No atlas solution found

### ISSUE THREAD

**Issue by Magicrafter13** [devkitPro/citro2d#5]
Today I added 2 new sprites, so I opened the sprites.t3s file and added the two file names to my large list of sprites.
I went to compile and it said 'No atlas solution found.'
If I remove the 2 lines (the 2 filenames) from the file again, it compiles fine.
Is there a sprite limit or something?

**Comment by fincs** [comment]
This is related to tex3ds, not citro2d; might want to open an issue there. Also, it's very likely you either have too many images, or they are too big.

**Comment by Magicrafter13** [comment]
okay, sorry I didn't know they were unrelated to each other
